### ISSUE TITLE
File descriptor warning

### ISSUE THREAD

**Issue by masterof0** [sonatype/chef-nexus-repository-manager#23]
I am currently running 3.7.1 and am getting a file descriptor error when logging into the UI as admin. I found the following ticket; NEXUS-14857 that reference the same issue and took a look at the config file that is referenced. The following lines are present in the limits.conf file which sould resolve the problem, but I am still getting the warning 

`nexus hard nofile 65536 ` 
`nexus soft nofile 65536`

**Comment by robbo10** [comment]
@masterof0  - I'm getting the same warning, did you manage to resolve this? 

Thanks
