### ISSUE TITLE
nexus3 install fails

### ISSUE THREAD

**Issue by emichaf** [sonatype/chef-nexus-repository-manager#26]
using release-0.5.20180105-135811.666c150.

And running nexus3 install via Docker file: https://github.com/sonatype/docker-nexus3/blob/master/Dockerfile

Receives the following error:
Recipe: java::set_java_home
  * directory[/etc/profile.d] action create (up to date)
  * template[/etc/profile.d/jdk.sh] action create
    - create new file /etc/profile.d/jdk.sh
    - update content in file /etc/profile.d/jdk.sh from none to b2915a
    --- /etc/profile.d/jdk.sh   2018-01-17 14:50:30.584455369 +0000
    +++ /etc/profile.d/.chef-jdk20180117-79-1t39dff.sh  2018-01-17 14:50:30.584455369 +0000
    @@ -1 +1,2 @@
    +export JAVA_HOME=/opt/java
    - change mode from '' to '0755'
Recipe: java::oracle
  * yum_package[tar] action install (up to date)
  * java_ark[jdk] action install
    * yum_package[curl for download_direct_from_oracle] action install (up to date)
    - download oracle tarball straight from the server[2018-01-17T14:50:37+00:00] FATAL: Failed to extract file server-jre-8u152-linux-x64.tar.gz!

  Running handlers:
[2018-01-17T14:50:37+00:00] ERROR: Running exception handlers
  Running handlers complete
[2018-01-17T14:50:37+00:00] ERROR: Exception handlers complete
  Chef Client failed. 2 resources updated in 09 seconds
[2018-01-17T14:50:37+00:00] FATAL: Stacktrace dumped to /etc/chef/local-mode-cache/cache/chef-stacktrace.out
[2018-01-17T14:50:37+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2018-01-17T14:50:37+00:00] ERROR: exit
[2018-01-17T14:50:37+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
ERROR: Service 'mynexus3' failed to build: The command '/bin/sh -c curl -L https://www.getchef.com/chef/install.sh | bash     && /opt/chef/embedded/bin/erb /var/chef/solo.json.erb > /var/chef/solo.json     && chef-solo        --recipe-url ${NEXUS_REPOSITORY_MANAGER_COOKBOOK_URL}        --json-attributes /var/chef/solo.json     && rpm -qa *chef* | xargs rpm -e     && rpm --rebuilddb     && rm -rf /etc/chef     && rm -rf /opt/chefdk     && rm -rf /var/cache/yum     && rm -rf /var/chef' returned a non-zero code: 1

**Comment by bigspotteddog** [comment]
server-jre-8u152 has been removed from the download site.

We will need to upgrade to either:

http://download.oracle.com/otn-pub/java/jdk/8u161-b12/2f38c3b165be4555a1fa6e98c45e0808/server-jre-8u161-linux-x64.tar.gz

or

http://download.oracle.com/otn-pub/java/jdk/8u162-b12/0da788060d494f5095bf8624735fa2f1/server-jre-8u162-linux-x64.tar.gz

**Comment by emichaf** [comment]
Thnx, updated the Dockerfile!
