### ISSUE TITLE
Question: why is systemd type set to "simple"

### ISSUE THREAD

**Issue by Brantone** [sonatype/chef-nexus-repository-manager#32]
Looking at https://help.sonatype.com/display/NXRM3/Run+as+a+Service#RunasaService-systemd and prescribed `Type=forking`, whereas cookbook is `Type=simple` ... curious if reason for that?
https://github.com/sonatype/chef-nexus-repository-manager/blob/master/recipes/systemd.rb#L13

**Comment by whyjustin** [comment]
@bigspotteddog @fernau ^^^ ?

**Comment by fernau** [comment]
The reason behind this is that for simplicity we would like to use the same startup script for both systemd and docker environments. Because docker works much better with processes that stay in the foreground and systemd supports both we decided to use `Type=simple` on systemd.

**Comment by Brantone** [comment]
Is the simplicity between systemd+docker envs risking optimizations though? (ex: make it a template?)
For Nexus in a production environment, is `Type=forking` still recommended and more preferred than `Type=simple`? Thx again.

**Comment by fernau** [comment]
I can't see any optimisation being affected by the process being managed in `forking` or `simple` mode. This only tells systemd how to launch and manage the process, but it doesn't affect the application itself.
The systemd configuration in the documentation is an example and you can always adapt it to make it work best with your local environment.
I am more concerned with the risks with creating duplicate and later possibly diverging configurations. There is no optimisation benefit of using `forking` over `simple` and I don't want to introduce additional complexity for no good reason.
Historically unix services typically run in `forking` mode, but if you use a modern service manager like systemd or upstart this has become irrelevant except that some services only support one or the other. The nexus `bin/nexus` startup script conveniently supports both by using the `run` or `start` parameters, respectively.

**Comment by Brantone** [comment]
Understood. Thanks for the thorough explanation 👍
